language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - r.roca@alumnos.upm.es
script:
#Test unitario y de integracion en develop
- mvn verify
